services:
  - type: web
    name: go-country-pulse
    env: go
    plan: free
    buildCommand: |
      if [ ! -f go.mod ]; then
        go mod init country-pulse
      fi
      go mod tidy
      go build -o country-pulse .
    startCommand: ./country-pulse
